import "@testing-library/jest-dom/vitest";

import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";

import { phononAnimationFixture } from "../phonon-animation/phononAnimationTestFixture";
import type { BZRendererEngine, BZRendererEngineFactory, BZRendererSnapshot } from "../brillouin-zone/brillouinZoneTypes";
import { BandBZLinkedView } from "./BandBZLinkedView";
import { bandBZArtifacts } from "./bandBZLinkTestFixture";

function fakeEngine() {
  let selection:BZRendererSnapshot["selection"]=null;
  const snapshot=():BZRendererSnapshot=>({state:"rendered",graphicsContext:"webgl2",rendererVersion:"185",projection:"perspective",cameraPosition:[4,4,4],cameraTarget:[0,0,0],cameraUp:[0,0,1],selection,pointScreenPositions:[],faceScreenPositions:[],metrics:{artifactBytes:8000,vertexCount:8,edgeCount:12,faceCount:6,triangleCount:12,pointCount:4,pathSegmentCount:6,visibleLabelCount:4,drawCalls:6,geometries:5,materials:8,textures:0,canvasCount:1,contextCount:1,mappingMs:1,initializationMs:2,firstFrameMs:2}});
  const engine:BZRendererEngine={resetCamera:vi.fn(),fit:vi.fn(),setCameraPreset:vi.fn(),setProjection:vi.fn(),setVisibility:vi.fn(),setOpacity:vi.fn(),setVariant:vi.fn(),setSelection:vi.fn((next)=>{selection=next;}),keyboardCamera:vi.fn(),exportPng:vi.fn(),snapshot,dispose:vi.fn()};
  return engine;
}

describe("BandBZLinkedView",()=>{
  it("links a pinned band sample into one existing BZ marker and preserves branch identity",async()=>{const engine=fakeEngine();render(<BandBZLinkedView artifacts={bandBZArtifacts()} capabilityOverride engineFactory={async()=>engine}/>);await waitFor(()=>expect(screen.getByTestId("brillouin-zone-renderer-state")).toHaveTextContent("rendered"));expect(screen.getByTestId("band-bz-compatibility-status")).toHaveTextContent("compatible");await userEvent.selectOptions(screen.getByTestId("band-bz-branch"),"2");const sample=screen.getByTestId("band-bz-chart").querySelector('[data-qpoint-index="1"]')!;fireEvent.click(sample);expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("sampled_reciprocal_point");expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("2");await waitFor(()=>expect(engine.setSelection).toHaveBeenLastCalledWith(expect.objectContaining({kind:"reciprocal_sample",id:"q-1"})));});
  it("maps BZ point and whole-segment picks back to band identity without guessing a branch",async()=>{const engine=fakeEngine();let args:Parameters<BZRendererEngineFactory>[0]|undefined;render(<BandBZLinkedView artifacts={bandBZArtifacts()} capabilityOverride engineFactory={async(value)=>{args=value;return engine;}}/>);await waitFor(()=>expect(args).toBeDefined());const point=args!.scene.points[0];act(()=>args!.onSelection({kind:"point",id:point.id}));expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("high_symmetry_point");expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("not inferred");const segment=args!.scene.segments.find((item)=>item.variantId===args!.scene.selectedVariantId)!;act(()=>args!.onSelection({kind:"segment",id:segment.id,variantId:segment.variantId}));expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("path_segment");expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent(segment.id);});
  it("enables animation handoff only for the exact canonical mode q-point and branch",async()=>{const animation=phononAnimationFixture();const artifacts=bandBZArtifacts(animation.source.band_sha256);const band=artifacts.find((item)=>item.name==="phonon_band.json")!;const payload=band.content as any;const mode=animation.mode.mode;payload.branches[mode.branch_index].frequencies[mode.qpoint_index]=mode.frequency;artifacts.push({id:"animation",type:"phonon_animation_json",name:"phonon_animation.json",content:animation,contentHash:"c".repeat(64)} as any);render(<><div data-testid="phonon-animation-preview-panel"/><BandBZLinkedView artifacts={artifacts} capabilityOverride engineFactory={async()=>fakeEngine()}/></>);await waitFor(()=>expect(screen.getByTestId("brillouin-zone-renderer-state")).toHaveTextContent("rendered"));await userEvent.selectOptions(screen.getByTestId("band-bz-branch"),String(mode.branch_index));fireEvent.click(screen.getByTestId("band-bz-chart").querySelector(`[data-qpoint-index="${mode.qpoint_index}"]`)!);expect(screen.getByTestId("band-bz-animation-status")).toHaveTextContent("Exact canonical mode handoff available");expect(screen.getByRole("button",{name:"Open phonon animation"})).toBeEnabled();});
  it("clears pinned state on artifact replacement and supports mobile panel tabs and Escape",async()=>{const first=bandBZArtifacts();const engine=fakeEngine();const view=render(<BandBZLinkedView artifacts={first} capabilityOverride engineFactory={async()=>engine}/>);await waitFor(()=>expect(screen.getByTestId("brillouin-zone-renderer-state")).toHaveTextContent("rendered"));fireEvent.click(screen.getByTestId("band-bz-chart").querySelector('[data-qpoint-index="0"]')!);expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("q-point");fireEvent.keyDown(screen.getByTestId("band-bz-linked-view"),{key:"Escape"});expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("No reciprocal selection");await userEvent.click(screen.getByRole("tab",{name:"3D BZ"}));expect(screen.getByRole("tab",{name:"3D BZ"})).toHaveAttribute("aria-selected","true");view.rerender(<BandBZLinkedView artifacts={bandBZArtifacts("d".repeat(64))} capabilityOverride engineFactory={async()=>fakeEngine()}/>);await waitFor(()=>expect(screen.getByTestId("band-bz-shared-inspector")).toHaveTextContent("No reciprocal selection"));});
  it("blocks linked rendering for mismatched primitive identity before engine initialization",()=>{const artifacts=bandBZArtifacts();const band=artifacts.find((item)=>item.name==="phonon_band.json")!;((band.content as any).real_space_lattice_angstrom[0][0])+=.2;const factory=vi.fn(async()=>fakeEngine());render(<BandBZLinkedView artifacts={artifacts} capabilityOverride engineFactory={factory}/>);expect(screen.getByTestId("band-bz-linked-fallback")).toHaveTextContent("BAND_BZ_PRIMITIVE_LATTICE_MISMATCH");expect(factory).not.toHaveBeenCalled();});
});
