import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

import type { IsosurfaceMesh, ValidatedVolumetricGrid, VolumeVector3, VolumetricRendererEngine, VolumetricRendererSnapshot, VolumetricStructureOverlay, VolumetricSurfacePick } from "./volumetricViewerTypes";
import { VolumetricViewerError } from "./volumetricViewerTypes";

export async function createVolumetricRendererEngine(args: Readonly<{
  container: HTMLElement;
  grid: ValidatedVolumetricGrid;
  fieldId: string;
  meshes: readonly IsosurfaceMesh[];
  overlay: VolumetricStructureOverlay | null;
  onSurfacePick?: (pick: VolumetricSurfacePick | null) => void;
  onAtomPick?: (siteIndex: number | null) => void;
  onContextLost: () => void;
}>): Promise<VolumetricRendererEngine> {
  const {container,grid,fieldId,meshes,overlay,onSurfacePick,onAtomPick,onContextLost}=args;
  if(typeof document==="undefined"||typeof window==="undefined")throw new VolumetricViewerError("VOLUME_VIEWER_WEBGL_UNSUPPORTED","Graphics are unavailable outside a browser.");
  const width=Math.max(320,container.clientWidth||720),height=Math.max(320,container.clientHeight||480);
  let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:"high-performance"});}catch{throw new VolumetricViewerError("VOLUME_VIEWER_WEBGL_UNSUPPORTED","The browser could not initialize WebGL.");}
  renderer.setPixelRatio(Math.min(Math.max(window.devicePixelRatio||1,1),2));renderer.setSize(width,height,false);renderer.setClearColor(0xf3f6f7,1);renderer.localClippingEnabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.dataset.testid="volumetric-renderer-canvas";renderer.domElement.setAttribute("role","img");renderer.domElement.setAttribute("aria-label","Interactive volumetric isosurface renderer");renderer.domElement.tabIndex=-1;container.append(renderer.domElement);
  const scene=new THREE.Scene();const root=new THREE.Group();root.name="validated-volumetric-scene";scene.add(root);let projection:"perspective"|"orthographic"="perspective";const frame=frameFor(grid,meshes,overlay);let camera:THREE.PerspectiveCamera|THREE.OrthographicCamera=new THREE.PerspectiveCamera(42,width/height,frame.near,frame.far);camera.position.copy(frame.position);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(frame.target);controls.enableDamping=false;controls.enablePan=true;renderer.domElement.style.touchAction="pan-y";
  const surfaceMaterials:THREE.MeshStandardMaterial[]=[];const surfaceMeshes:THREE.Mesh[]=[];const colors=[0xe85d75,0x2f80ed,0x7b61ff,0x0b8f8f];
  for(const [index,mesh] of meshes.entries()){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.BufferAttribute(mesh.positions,3));geometry.setAttribute("normal",new THREE.BufferAttribute(mesh.normals,3));geometry.setIndex(new THREE.BufferAttribute(mesh.indices,1));geometry.computeBoundingBox();geometry.computeBoundingSphere();const material=new THREE.MeshStandardMaterial({color:colors[index%colors.length],transparent:true,opacity:.62,side:THREE.DoubleSide,roughness:.38,metalness:.03,depthWrite:false});material.clippingPlanes=[];surfaceMaterials.push(material);const surface=new THREE.Mesh(geometry,material);surface.name=`isosurface-${mesh.layerId}`;surface.userData={fieldId,layerId:mesh.layerId,isovalue:mesh.isovalue,meshHash:mesh.meshHash};surfaceMeshes.push(surface);root.add(surface);}
  const overlayObjects:THREE.Object3D[]=[];let atomMeshes:THREE.InstancedMesh[]=[];let atomGeometry:THREE.SphereGeometry|null=null;const atomMaterials=new Map<string,THREE.MeshStandardMaterial>();
  if(overlay){atomGeometry=new THREE.SphereGeometry(1,16,10);const groups=new Map<string,typeof overlay.atoms>();for(const atom of overlay.atoms)groups.set(atom.color,[...(groups.get(atom.color)||[]),atom]);for(const [color,atoms] of groups){const material=new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.02});atomMaterials.set(color,material);const mesh=new THREE.InstancedMesh(atomGeometry,material,atoms.length);mesh.name=`volumetric-atoms-${color}`;const matrix=new THREE.Matrix4();for(const [index,atom] of atoms.entries()){matrix.compose(new THREE.Vector3(...atom.position),new THREE.Quaternion(),new THREE.Vector3(atom.radius,atom.radius,atom.radius));mesh.setMatrixAt(index,matrix);}mesh.instanceMatrix.needsUpdate=true;mesh.userData={siteIndices:atoms.map((atom)=>atom.siteIndex)};atomMeshes.push(mesh);root.add(mesh);overlayObjects.push(mesh);}}
  let bondGeometry:THREE.BufferGeometry|null=null;let bondMaterial:THREE.LineBasicMaterial|null=null;let bondLines:THREE.LineSegments|null=null;if(overlay?.bonds.length){bondGeometry=lineGeometry(overlay.bonds.flatMap((bond)=>[bond.start,bond.end]));bondMaterial=new THREE.LineBasicMaterial({color:0x536878,transparent:true,opacity:.7});bondLines=new THREE.LineSegments(bondGeometry,bondMaterial);bondLines.name="volumetric-structure-bonds";root.add(bondLines);overlayObjects.push(bondLines);}
  let cellGeometry:THREE.BufferGeometry|null=null;let cellMaterial:THREE.LineBasicMaterial|null=null;let cellLines:THREE.LineSegments|null=null;if(grid.periodic){const vectors:[VolumeVector3,VolumeVector3,VolumeVector3]=[scaleRow(grid.stepMatrix[0],grid.shape[0]),scaleRow(grid.stepMatrix[1],grid.shape[1]),scaleRow(grid.stepMatrix[2],grid.shape[2])];cellGeometry=lineGeometry(cellEdges(grid.origin,vectors));cellMaterial=new THREE.LineBasicMaterial({color:0x1f6f8b,transparent:true,opacity:.9});cellLines=new THREE.LineSegments(cellGeometry,cellMaterial);cellLines.name="volumetric-unit-cell";root.add(cellLines);}
  const ambient=new THREE.AmbientLight(0xffffff,1.35),key=new THREE.DirectionalLight(0xffffff,2.2);key.position.copy(frame.position);scene.add(ambient,key);let surfaceVisible=true,structureVisible=true,clippingEnabled=false,clipAxis:0|1|2=2,clipOffset=0,selected:VolumetricSurfacePick|null=null,disposed=false,contextLost=false;let clippingPlanes:THREE.Plane[]=[];
  const snapshot=():VolumetricRendererSnapshot=>Object.freeze({state:contextLost?"context_lost":disposed?"disposed":"rendered",canvasCount:container.querySelectorAll("canvas").length,contextCount:disposed?0:1,vertexCount:meshes.reduce((sum,mesh)=>sum+mesh.vertexCount,0),triangleCount:meshes.reduce((sum,mesh)=>sum+mesh.triangleCount,0),layerCount:meshes.length,drawCalls:renderer.info.render.calls,geometries:renderer.info.memory.geometries,materials:surfaceMaterials.length+atomMaterials.size+(bondMaterial?1:0)+(cellMaterial?1:0),cameraProjection:projection,clippingEnabled,surfaceVisible,structureVisible});
  const render=()=>{if(disposed||contextLost)return;renderer.render(scene,camera);publish();};
  controls.addEventListener("change",render);
  const publish=()=>{(window as unknown as {__mdiVolumetricRendererEvidence?:VolumetricRendererSnapshot}).__mdiVolumetricRendererEvidence=snapshot();};
  const applyClip=()=>{clippingPlanes=clippingEnabled?[new THREE.Plane(new THREE.Vector3(...axisVector(clipAxis)),clipOffset)]:[];for(const material of surfaceMaterials)material.clippingPlanes=clippingPlanes;};
  const setProjection=(next:"perspective"|"orthographic")=>{if(next===projection)return;const position=camera.position.clone(),target=controls.target.clone();projection=next;if(next==="perspective"){const nextCamera=new THREE.PerspectiveCamera(42,width/height,frame.near,frame.far);nextCamera.position.copy(position);camera=nextCamera;}else{const half=Math.max(frame.radius,1)*1.35;const nextCamera=new THREE.OrthographicCamera(-half*width/height,half*width/height,half,-half,frame.near,frame.far);nextCamera.position.copy(position);camera=nextCamera;}(controls as unknown as {object:THREE.Camera}).object=camera;controls.target.copy(target);controls.update();render();};
  const resetCamera=()=>{camera.position.copy(frame.position);controls.target.copy(frame.target);if(camera instanceof THREE.PerspectiveCamera){camera.near=frame.near;camera.far=frame.far;camera.aspect=width/height;camera.updateProjectionMatrix();}else{updateOrtho(camera,frame,width,height);}controls.update();render();};
  const fitSurface=()=>{const next=frameFor(grid,meshes,null);camera.position.copy(next.position);controls.target.copy(next.target);render();};const fitStructure=()=>{const next=frameFor(grid,[],overlay);camera.position.copy(next.position);controls.target.copy(next.target);render();};
  const pick=(event:PointerEvent)=>{if(disposed||contextLost)return;const bounds=renderer.domElement.getBoundingClientRect();const pointer=new THREE.Vector2(((event.clientX-bounds.left)/bounds.width)*2-1,-((event.clientY-bounds.top)/bounds.height)*2+1);const raycaster=new THREE.Raycaster();raycaster.setFromCamera(pointer,camera);const atomHit=raycaster.intersectObjects(atomMeshes,false)[0];if(atomHit?.instanceId!==undefined){const ids=Array.isArray(atomHit.object.userData.siteIndices)?atomHit.object.userData.siteIndices:[];onAtomPick?.(Number.isSafeInteger(ids[atomHit.instanceId])?ids[atomHit.instanceId]:null);return;}const surfaceHit=raycaster.intersectObjects(surfaceMeshes,false)[0];if(!surfaceHit||typeof surfaceHit.faceIndex!=="number"){onSurfacePick?.(null);return;}const layer=surfaceHit.object.userData as {layerId:string;isovalue:number;meshHash:string};const pickValue:VolumetricSurfacePick=Object.freeze({fieldId,layerId:layer.layerId,isovalue:layer.isovalue,triangleIndex:surfaceHit.faceIndex,cartesianPosition:Object.freeze([surfaceHit.point.x,surfaceHit.point.y,surfaceHit.point.z]) as VolumeVector3,interpolatedFieldValue:layer.isovalue,meshHash:layer.meshHash});selected=pickValue;onSurfacePick?.(selected);render();};
  renderer.domElement.addEventListener("pointerup",pick);const onLost=(event:Event)=>{event.preventDefault();contextLost=true;onContextLost();};renderer.domElement.addEventListener("webglcontextlost",onLost,false);const resize=()=>{if(disposed)return;const nextWidth=Math.max(320,container.clientWidth||width),nextHeight=Math.max(320,container.clientHeight||height);if(camera instanceof THREE.PerspectiveCamera){camera.aspect=nextWidth/nextHeight;camera.updateProjectionMatrix();}else updateOrtho(camera,frame,nextWidth,nextHeight);renderer.setSize(nextWidth,nextHeight,false);render();};const observer=typeof ResizeObserver==="function"?new ResizeObserver(resize):null;observer?.observe(container);window.addEventListener("resize",resize);applyClip();controls.update();render();
  const engine:VolumetricRendererEngine={setSurfaceVisible:(visible)=>{surfaceVisible=visible;surfaceMeshes.forEach((mesh)=>mesh.visible=visible);render();},setLayerVisible:(layerId,visible)=>{surfaceMeshes.filter((mesh)=>mesh.userData.layerId===layerId).forEach((mesh)=>mesh.visible=visible&&surfaceVisible);render();},setStructureVisible:(visible)=>{structureVisible=visible;overlayObjects.forEach((object)=>object.visible=visible);render();},setCellVisible:(visible)=>{if(cellLines)cellLines.visible=visible;render();},setOpacity:(opacity)=>{const bounded=Math.min(.9,Math.max(.1,Number.isFinite(opacity)?opacity:.62));surfaceMaterials.forEach((material)=>material.opacity=bounded);render();},setProjection, setClipping:(enabled,axis,offset)=>{clippingEnabled=enabled;clipAxis=axis;clipOffset=Number.isFinite(offset)?Math.max(-10000,Math.min(10000,offset)):0;applyClip();render();},resetCamera,fitSurface,fitStructure,setSelection:(pickValue)=>{selected=pickValue;render();},snapshot,render,exportPng:async(exportWidth,exportHeight,pixelRatio)=>{if(!Number.isSafeInteger(exportWidth)||!Number.isSafeInteger(exportHeight)||exportWidth<256||exportHeight<256||exportWidth>4096||exportHeight>4096||exportWidth*exportHeight*pixelRatio*pixelRatio>16_777_216)throw new VolumetricViewerError("VOLUME_VIEWER_MESH_CAP_EXCEEDED","PNG export exceeds the bounded pixel budget.");const oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio();try{renderer.setPixelRatio(pixelRatio);renderer.setSize(exportWidth,exportHeight,false);render();const blob=await new Promise<Blob>((resolve,reject)=>renderer.domElement.toBlob((value)=>value?resolve(value):reject(new Error("blob")),"image/png"));return blob;}finally{renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);render();}},dispose:()=>{if(disposed)return;disposed=true;observer?.disconnect();window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("pointerup",pick);renderer.domElement.removeEventListener("webglcontextlost",onLost);controls.removeEventListener("change",render);controls.dispose();surfaceMeshes.forEach((mesh)=>{mesh.geometry.dispose();(mesh.material as THREE.Material).dispose();root.remove(mesh);});atomGeometry?.dispose();atomMaterials.forEach((material)=>material.dispose());bondGeometry?.dispose();bondMaterial?.dispose();cellGeometry?.dispose();cellMaterial?.dispose();renderer.dispose();renderer.domElement.remove();publish();}};
  return engine;
}

function frameFor(grid:ValidatedVolumetricGrid,meshes:readonly IsosurfaceMesh[],overlay:VolumetricStructureOverlay|null){const points:THREE.Vector3[]=[];meshes.forEach((mesh)=>{for(let index=0;index<mesh.positions.length;index+=3)points.push(new THREE.Vector3(mesh.positions[index],mesh.positions[index+1],mesh.positions[index+2]));});overlay?.atoms.forEach((atom)=>points.push(new THREE.Vector3(...atom.position)));if(!points.length){const extent:[VolumeVector3,VolumeVector3,VolumeVector3]=[scaleRow(grid.stepMatrix[0],grid.shape[0]),scaleRow(grid.stepMatrix[1],grid.shape[1]),scaleRow(grid.stepMatrix[2],grid.shape[2])];points.push(new THREE.Vector3(...grid.origin),new THREE.Vector3(grid.origin[0]+extent[0][0]+extent[1][0]+extent[2][0],grid.origin[1]+extent[0][1]+extent[1][1]+extent[2][1],grid.origin[2]+extent[0][2]+extent[1][2]+extent[2][2]));}const box=new THREE.Box3().setFromPoints(points),sphere=box.getBoundingSphere(new THREE.Sphere()),radius=Math.max(sphere.radius,1);return{radius,target:sphere.center.clone(),position:sphere.center.clone().add(new THREE.Vector3(radius*1.8,radius*1.8,radius*1.35)),near:Math.max(radius/100,.01),far:Math.max(radius*40,10)};}
function lineGeometry(points:readonly VolumeVector3[]){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(points.flatMap((point)=>[...point]),3));return geometry;}
function cellEdges(origin:VolumeVector3,vectors:readonly[VolumeVector3,VolumeVector3,VolumeVector3]){const corners=[origin,add(origin,vectors[0]),add(add(origin,vectors[0]),vectors[1]),add(origin,vectors[1]),add(origin,vectors[2]),add(add(origin,vectors[0]),vectors[2]),add(add(add(origin,vectors[0]),vectors[1]),vectors[2]),add(add(origin,vectors[1]),vectors[2])];const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];return edges.flatMap(([a,b])=>[corners[a],corners[b]]);}
function add(a:VolumeVector3,b:VolumeVector3):VolumeVector3{return[a[0]+b[0],a[1]+b[1],a[2]+b[2]];}
function scaleRow(row:VolumeVector3,value:number):VolumeVector3{return[row[0]*value,row[1]*value,row[2]*value];}
function axisVector(axis:0|1|2):VolumeVector3{return axis===0?[1,0,0]:axis===1?[0,1,0]:[0,0,1];}
function updateOrtho(camera:THREE.OrthographicCamera,frame:{radius:number},width:number,height:number){const half=Math.max(frame.radius,1)*1.35;camera.left=-half*width/height;camera.right=half*width/height;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();}
