import { describe, expect, it, vi } from "vitest";
import { VolumetricSliceWorkerClient, type VolumetricSliceWorkerLike } from "./volumetricSliceWorkerClient";

function workerHarness(autoReply = true) { const listeners = new Map<string, EventListener>(); const messages: Array<{ requestId: number }> = []; const worker: VolumetricSliceWorkerLike = { postMessage: vi.fn((message: { requestId: number }) => { messages.push(message); if (autoReply) queueMicrotask(() => listeners.get("message")?.({ data: { type: "success", requestId: message.requestId, slice: { values: new Float64Array(1) }, calculationMs: 1 } } as unknown as Event)); }), terminate: vi.fn(), addEventListener: vi.fn((name: string, listener: EventListener) => listeners.set(name, listener)), removeEventListener: vi.fn((name: string) => listeners.delete(name)) }; return { worker, listeners, messages }; }
function request(buffer = new ArrayBuffer(4)) { return { type: "slice" as const, datasetHash: "d", fieldHash: "f", unit: "u", grid: {} as never, dtype: "float32" as const, fieldBuffer: buffer, axis: 0 as const, fractionalPosition: 0, maximumOutputValues: 1 }; }

describe("volumetric slice Worker lifecycle", () => {
  it("transfers one request, resolves the current result, and keeps the Worker for axis changes", async () => { const { worker } = workerHarness(); const client = new VolumetricSliceWorkerClient(() => worker); const buffer = new ArrayBuffer(4); const result = await client.sample(request(buffer)); expect(result.calculationMs).toBe(1); expect(worker.postMessage).toHaveBeenCalledWith(expect.objectContaining({ requestId: expect.any(Number) }), [buffer]); expect(worker.terminate).not.toHaveBeenCalled(); expect(client.snapshot().activeWorkerCount).toBe(1); client.dispose(); expect(worker.terminate).toHaveBeenCalledOnce(); });
  it("reuses one Worker across completed slice samples", async () => { const { worker } = workerHarness(); const factory = vi.fn(() => worker); const client = new VolumetricSliceWorkerClient(factory); await client.sample(request()); await client.sample(request()); expect(factory).toHaveBeenCalledOnce(); expect(worker.postMessage).toHaveBeenCalledTimes(2); client.dispose(); expect(worker.terminate).toHaveBeenCalledOnce(); });
  it("terminates stale synchronous work, ignores its late result, and disposes the replacement exactly once", async () => { const firstWorker = workerHarness(false); const secondWorker = workerHarness(false); const factory = vi.fn().mockReturnValueOnce(firstWorker.worker).mockReturnValueOnce(secondWorker.worker); const client = new VolumetricSliceWorkerClient(factory); const first = client.sample(request()).catch((error) => error); const second = client.sample(request()); firstWorker.listeners.get("message")?.({ data: { type: "success", requestId: firstWorker.messages[0].requestId, slice: { values: new Float64Array([9]) }, calculationMs: 9 } } as unknown as Event); secondWorker.listeners.get("message")?.({ data: { type: "success", requestId: secondWorker.messages[0].requestId, slice: { values: new Float64Array([1]) }, calculationMs: 1 } } as unknown as Event); await expect(first).resolves.toMatchObject({ code: "VOLUME_VIEWER_WORKER_FAILED" }); await expect(second).resolves.toMatchObject({ calculationMs: 1 }); expect(firstWorker.worker.terminate).toHaveBeenCalledOnce(); expect(secondWorker.worker.terminate).not.toHaveBeenCalled(); client.dispose(); client.dispose(); expect(secondWorker.worker.terminate).toHaveBeenCalledOnce(); expect(client.snapshot()).toMatchObject({ activeWorkerCount: 0, disposed: true }); });
});
