import type { ImageOffset, RenderAtom, RenderBond, RenderVector3, ValidatedRenderScene } from "../viewer-scene/viewerSceneRendererTypes";
import { animationDisplacements, type PhononAnimationPackage, validatePhononAnimation } from "./phononAnimationContract";

const COLORS=["#2f7f8f","#d56a45","#7b61a8","#4f8d58","#c08b28","#476aa3","#a74f6f","#64748b"] as const;
const RADII:Readonly<Record<string,number>>=Object.freeze({H:.38,C:.68,N:.65,O:.62,Na:.9,Si:.78,Cl:.82});
export type MappedPhononAnimation=Readonly<{scene:ValidatedRenderScene;vectors:readonly Readonly<{start:RenderVector3;end:RenderVector3}>[];displacements:readonly RenderVector3[];phase:number;mapMs:number}>;
export type PhononAnimationMappingResult={readonly ok:true;readonly package:PhononAnimationPackage}|{readonly ok:false;readonly errors:readonly string[]};

export function validatePhononAnimationForViewer(payload:unknown):PhononAnimationMappingResult{const validation=validatePhononAnimation(payload);return validation.valid?{ok:true,package:payload as PhononAnimationPackage}:{ok:false,errors:validation.errors};}
export function mapPhononAnimationFrame(payload:PhononAnimationPackage,phase:number,displayScale?:number):MappedPhononAnimation{
  const started=performance.now();const validation=validatePhononAnimation(payload);if(!validation.valid)throw new Error(validation.errors[0]);
  const structure=payload.structure as Record<string,any>;const lattice=Object.freeze((structure.lattice as number[][]).map((row)=>tuple(row))) as ValidatedRenderScene["lattice"]["matrix"];const repeat=Object.freeze([...(payload.supercell.repeat as number[])]) as ImageOffset;
  const species=[...new Set((structure.sites as Array<Record<string,any>>).map((site)=>String(site.species)))].sort();const atoms:RenderAtom[]=[];const vectors:Readonly<{start:RenderVector3;end:RenderVector3}>[]=[];const allDisplacements:RenderVector3[]=[];
  for(let i=0;i<repeat[0];i++)for(let j=0;j<repeat[1];j++)for(let k=0;k<repeat[2];k++){const offset=Object.freeze([i,j,k]) as ImageOffset;const displacement=animationDisplacements(payload,phase,offset,displayScale);const translation=translate(offset,lattice);(structure.sites as Array<Record<string,any>>).forEach((site,index)=>{const reference=tuple((site.cartesian as number[]).map((value,axis)=>value+translation[axis]));const current=tuple(reference.map((value,axis)=>value+displacement[index][axis]));const ref=Object.freeze({siteIndex:index,imageOffset:offset});atoms.push(Object.freeze({id:`phonon:${index}@[${offset.join(",")}]`,siteIndex:index,ref,species:String(site.species),label:`${site.species}${index+1}`,element:String(site.species),occupancy:1,position:current,canonicalPosition:reference,fractionalPosition:tuple(site.fractional as number[]),radius:RADII[String(site.species)]??.72,color:COLORS[species.indexOf(String(site.species))%COLORS.length]}));vectors.push(Object.freeze({start:reference,end:current}));allDisplacements.push(displacement[index]);});}
  const bonds=mapBonds(structure.bonds,atoms);const displayMatrix=Object.freeze(lattice.map((row,axis)=>tuple(row.map((value)=>value*repeat[axis])))) as ValidatedRenderScene["lattice"]["matrix"];
  const scene=Object.freeze({contractVersion:"phonon_animation.v1",schemaVersion:"phase10h5.phonon_animation.v1",atoms:Object.freeze(atoms),bonds:Object.freeze(bonds),lattice:Object.freeze({matrix:lattice}),displayLattice:Object.freeze({matrix:displayMatrix}),supercellRepeat:repeat,source:Object.freeze({resourceId:String(payload.mode.mode.mode_id),filename:"phonon_animation.json",parser:"validated-phonon-animation"}),formula:String(structure.formula),warnings:Object.freeze([...(payload.warnings as string[])])}) satisfies ValidatedRenderScene;
  return Object.freeze({scene,vectors:Object.freeze(vectors),displacements:Object.freeze(allDisplacements),phase,mapMs:performance.now()-started});
}
function mapBonds(value:unknown,atoms:readonly RenderAtom[]):RenderBond[]{if(!Array.isArray(value))return[];const byKey=new Map(atoms.map((atom)=>[`${atom.siteIndex}:${atom.ref.imageOffset.join(":")}`,atom]));const result:RenderBond[]=[];for(const atom of atoms)for(const bond of value){if(!record(bond)||!Number.isSafeInteger(bond.from)||!Number.isSafeInteger(bond.to)||atom.siteIndex!==bond.from)continue;const target=byKey.get(`${bond.to}:${atom.ref.imageOffset.join(":")}`);if(!target)continue;const dx=target.position[0]-atom.position[0],dy=target.position[1]-atom.position[1],dz=target.position[2]-atom.position[2];const distance=Math.hypot(dx,dy,dz);if(distance<=1e-9)continue;result.push(Object.freeze({id:`phonon-bond:${bond.from}:${bond.to}@[${atom.ref.imageOffset.join(",")}]`,fromSiteIndex:atom.siteIndex,toSiteIndex:target.siteIndex,fromRef:atom.ref,toRef:target.ref,start:atom.position,end:target.position,displacementCartesian:tuple([dx,dy,dz]),distanceAngstrom:distance,source:"explicit_input",authoritative:false}));}return result.slice(0,8192);}
function translate(offset:ImageOffset,lattice:ValidatedRenderScene["lattice"]["matrix"]):RenderVector3{return tuple([offset[0]*lattice[0][0]+offset[1]*lattice[1][0]+offset[2]*lattice[2][0],offset[0]*lattice[0][1]+offset[1]*lattice[1][1]+offset[2]*lattice[2][1],offset[0]*lattice[0][2]+offset[1]*lattice[1][2]+offset[2]*lattice[2][2]]);}
function tuple(value:readonly number[]):RenderVector3{return Object.freeze([Number(value[0]),Number(value[1]),Number(value[2])]);}
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value);}
