"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import type { PeriodicSiteRef, RenderVector3, ViewerRendererEngine, ViewerRendererEngineFactory, ViewerRendererSnapshot } from "../viewer-scene/viewerSceneRendererTypes";
import { mapPhononAnimationFrame, validatePhononAnimationForViewer, type MappedPhononAnimation } from "./phononAnimationMapper";

const defaultEngineFactory:ViewerRendererEngineFactory=async(args)=>(await import("../viewer-scene/viewerSceneRendererEngine")).createThreeViewerEngine(args);
export type PhononAnimationSurfaceProps=Readonly<{payload:unknown;capabilityOverride?:boolean;reducedMotionOverride?:boolean;engineFactory?:ViewerRendererEngineFactory}>;

export function PhononAnimationSurface({payload,capabilityOverride,reducedMotionOverride,engineFactory=defaultEngineFactory}:PhononAnimationSurfaceProps){
  const validation=useMemo(()=>validatePhononAnimationForViewer(payload),[payload]);const animation=validation.ok?validation.package:null;
  const playback=animation?.playback as Record<string,any>|undefined;const display=animation?.display as Record<string,any>|undefined;
  const [phase,setPhase]=useState(()=>Number(playback?.initial_phase_radians??0));const [playing,setPlaying]=useState(false);const playingRef=useRef(false);playingRef.current=playing;
  const [speed,setSpeed]=useState(()=>Number(playback?.cycles_per_second??.5));const [scale,setScale]=useState(()=>Number(display?.display_scale??.15));
  const [showVectors,setShowVectors]=useState(()=>Boolean(display?.show_vectors??true));const [showTrails,setShowTrails]=useState(()=>Boolean(display?.show_trails??false));const [showBonds,setShowBonds]=useState(()=>Boolean(display?.show_bonds??true));const [showCell,setShowCell]=useState(()=>Boolean(display?.show_unit_cell??true));
  const [selected,setSelected]=useState<PeriodicSiteRef|null>(null);const [snapshot,setSnapshot]=useState<ViewerRendererSnapshot|null>(null);const [fallback,setFallback]=useState<string|null>(null);const [announcement,setAnnouncement]=useState("Phonon animation idle.");const [attempt,setAttempt]=useState(0);
  const [reducedDetected,setReducedDetected]=useState(false);const reducedMotion=reducedMotionOverride??reducedDetected;
  const hostRef=useRef<HTMLDivElement>(null);const engineRef=useRef<ViewerRendererEngine|null>(null);const frameRef=useRef<number|null>(null);const lastTimeRef=useRef<number|null>(null);const disposedRef=useRef(false);const trailsRef=useRef<Map<string,RenderVector3[]>>(new Map());
  const mapped=useMemo(()=>animation?mapPhononAnimationFrame(animation,phase,scale):null,[animation,phase,scale]);const mappedRef=useRef<MappedPhononAnimation|null>(mapped);mappedRef.current=mapped;
  const stop=useCallback((message?:string)=>{playingRef.current=false;setPlaying(false);if(frameRef.current!==null){cancelAnimationFrame(frameRef.current);frameRef.current=null;}lastTimeRef.current=null;if(message)setAnnouncement(message);},[]);
  const onPick=useCallback((ref:PeriodicSiteRef|null)=>{if(playingRef.current)stop("Playback paused for atom inspection.");setSelected(ref);},[stop]);

  useEffect(()=>{const query=window.matchMedia?.("(prefers-reduced-motion: reduce)");const update=()=>setReducedDetected(Boolean(query?.matches));update();query?.addEventListener?.("change",update);return()=>query?.removeEventListener?.("change",update);},[]);
  useEffect(()=>{if(reducedMotion&&playing)stop("Playback paused because reduced motion is enabled.");},[playing,reducedMotion,stop]);
  useEffect(()=>{const visibility=()=>{if(document.hidden)stop("Playback paused because the tab is hidden.");};document.addEventListener("visibilitychange",visibility);return()=>document.removeEventListener("visibilitychange",visibility);},[stop]);

  useEffect(()=>{disposedRef.current=false;stop();engineRef.current?.dispose();engineRef.current=null;setFallback(null);setSelected(null);trailsRef.current.clear();if(!animation||!mapped)return()=>{disposedRef.current=true;};const supported=capabilityOverride??supportsWebGL();const host=hostRef.current;if(!supported||!host){setFallback(supported?"PHONON_ANIMATION_INITIALIZATION_FAILED":"PHONON_ANIMATION_WEBGL_UNSUPPORTED");return()=>{disposedRef.current=true;};}let cancelled=false;void engineFactory({container:host,scene:mapped.scene,pixelRatioCap:2,antialias:true,performanceTier:"interactive",onContextLost:()=>{stop();engineRef.current?.dispose();engineRef.current=null;setFallback("PHONON_ANIMATION_CONTEXT_LOST");setAnnouncement("Graphics context lost. Animation stopped; JSON remains available.");},onSitePick:onPick,onViewChange:()=>setSnapshot(engineRef.current?.snapshot()??null)}).then((engine)=>{if(cancelled){engine.dispose();return;}engineRef.current=engine;engine.setCellVisible(showCell);engine.setSupercellBoundaryVisible(true);engine.setLatticeAxesVisible(Boolean(display?.show_axes));engine.setBondsVisible(showBonds);engine.setDisplacementVectors(showVectors?mapped.vectors:[]);setSnapshot(engine.snapshot());setAnnouncement("Validated phonon mode loaded. Playback is paused.");}).catch(()=>{if(!cancelled)setFallback("PHONON_ANIMATION_INITIALIZATION_FAILED");});return()=>{cancelled=true;disposedRef.current=true;stop();engineRef.current?.dispose();engineRef.current=null;trailsRef.current.clear();};},[animation?.mode?.mode?.mode_id,attempt,capabilityOverride,engineFactory,onPick,stop]);

  useEffect(()=>{const engine=engineRef.current;if(!engine||!mapped)return;try{engine.updateDynamicScene(mapped.scene);engine.setBondsVisible(showBonds);engine.setCellVisible(showCell);engine.setDisplacementVectors(showVectors?mapped.vectors:[]);if(showTrails){mapped.scene.atoms.forEach((atom)=>{const key=atom.id;const path=trailsRef.current.get(key)??[];path.push(atom.position);if(path.length>Number(display?.trail_length??12))path.shift();trailsRef.current.set(key,path);});engine.setDisplacementTrails([...trailsRef.current.values()]);}else{trailsRef.current.clear();engine.setDisplacementTrails([]);}if(selected)engine.setSelection([selected]);setSnapshot(engine.snapshot());}catch{stop();setFallback("PHONON_ANIMATION_FRAME_UPDATE_FAILED");}},[mapped,selected,showBonds,showCell,showTrails,showVectors,display?.trail_length,stop]);

  useEffect(()=>{if(!playing||reducedMotion)return;const tick=(time:number)=>{if(disposedRef.current||!playingRef.current)return;const previous=lastTimeRef.current??time;lastTimeRef.current=time;const delta=Math.min(time-previous,100);setPhase((value)=>(value+delta/1000*speed*2*Math.PI)%(2*Math.PI));frameRef.current=requestAnimationFrame(tick);};frameRef.current=requestAnimationFrame(tick);return()=>{if(frameRef.current!==null){cancelAnimationFrame(frameRef.current);frameRef.current=null;}lastTimeRef.current=null;};},[playing,reducedMotion,speed]);

  if(!validation.ok)return <Fallback code={validation.errors[0]??"PHONON_ANIMATION_ARTIFACT_INVALID"} payload={payload}/>;if(!animation||!mapped)return <Fallback code="PHONON_ANIMATION_ARTIFACT_INVALID" payload={payload}/>;if(fallback)return <Fallback code={fallback} payload={payload} retry={()=>{setFallback(null);setAttempt((value)=>value+1);}}/>;
  const mode=animation.mode.mode as Record<string,any>;const imaginary=Boolean(animation.mode.provenance.imaginary_mode);const selectedAtom=selected?mapped.scene.atoms.find((atom)=>atom.siteIndex===selected.siteIndex&&atom.ref.imageOffset.every((value,index)=>value===selected.imageOffset[index])):null;const displacement=selectedAtom?[selectedAtom.position[0]-selectedAtom.canonicalPosition[0],selectedAtom.position[1]-selectedAtom.canonicalPosition[1],selectedAtom.position[2]-selectedAtom.canonicalPosition[2]]:null;
  const togglePlay=()=>{if(playing){stop("Phonon animation paused.");return;}if(reducedMotion){setAnnouncement("Reduced motion is enabled. Use the phase slider for a static preview.");return;}setSelected(null);setPlaying(true);setAnnouncement("Phonon animation playing. Display scale is visual only.");};
  return <section className="viewer-renderer-surface phonon-animation-surface" data-testid="phonon-animation-viewer" aria-label="Phonon mode animation" tabIndex={0}>
    <div className="viewer-renderer-toolbar"><div><strong>Phonon Mode Animation</strong><span data-testid="phonon-animation-state">{playing?"playing":"paused"}</span><span>q-point {mode.qpoint_index} [{mode.qpoint_coordinates.join(", ")}]</span><span>branch {mode.branch_index}</span><span>{mode.frequency} {mode.frequency_unit}</span></div><div className="viewer-renderer-controls"><button type="button" aria-label={playing?"Pause phonon animation":"Play phonon animation"} onClick={togglePlay}>{playing?"Pause":"Play"}</button><button type="button" onClick={()=>{stop();setPhase(0);}}>Reset phase</button><button type="button" onClick={()=>engineRef.current?.resetCamera()}>Reset camera</button></div></div>
    {imaginary?<p className="notice" data-testid="phonon-imaginary-warning">Imaginary mode: this is a static unstable-direction morph, not a stable time oscillation.</p>:null}{mode.degeneracy?<p className="notice" data-testid="phonon-degenerate-warning">The displayed basis is source-declared and arbitrary within its degenerate subspace.</p>:null}<p className="notice" data-testid="phonon-display-scale-warning">Display scale is a visualization scale in angstrom, not a measured physical amplitude.</p>{reducedMotion?<p className="notice" data-testid="phonon-reduced-motion">Reduced motion is enabled; playback remains paused and the phase slider provides static previews.</p>:null}
    <div className="phonon-animation-controls"><label>Mode <select data-testid="phonon-mode-selector" value={mode.mode_id} onChange={()=>{}}><option value={mode.mode_id}>q{mode.qpoint_index} / branch {mode.branch_index}</option></select></label><label>Phase <input data-testid="phonon-phase-slider" type="range" min={0} max={2*Math.PI} step={.01} value={phase} aria-valuetext={`${phase.toFixed(2)} radians`} onChange={(event)=>{stop();setPhase(Number(event.target.value));}}/></label><output data-testid="phonon-phase-value">{phase.toFixed(3)} rad</output><label>Speed <input data-testid="phonon-speed" type="range" min={.05} max={2} step={.05} value={speed} aria-valuetext={`${speed.toFixed(2)} cycles per second`} onChange={(event)=>setSpeed(Number(event.target.value))}/></label><label>Display scale <input data-testid="phonon-display-scale" type="range" min={.01} max={1} step={.01} value={scale} aria-valuetext={`${scale.toFixed(2)} angstrom visual scale`} onChange={(event)=>setScale(Number(event.target.value))}/></label><label><input type="checkbox" checked={showVectors} onChange={(event)=>setShowVectors(event.target.checked)}/>Vectors</label><label><input type="checkbox" checked={showTrails} onChange={(event)=>setShowTrails(event.target.checked)}/>Trails</label><label><input type="checkbox" checked={showBonds} onChange={(event)=>setShowBonds(event.target.checked)}/>Bonds</label><label><input type="checkbox" checked={showCell} onChange={(event)=>setShowCell(event.target.checked)}/>Cell</label></div>
    <div ref={hostRef} className="viewer-renderer-canvas-host" data-testid="phonon-animation-canvas-host"><span className="canvas-fallback">Validated phonon mode canvas</span></div>
    <div className="trajectory-inspector" data-testid="phonon-animation-inspector"><h3>Mode inspector</h3><dl><dt>Mode ID</dt><dd>{mode.mode_id}</dd><dt>Supercell</dt><dd>{animation.supercell.repeat.join(" x ")}</dd><dt>Phase</dt><dd>{phase.toFixed(3)} rad</dd><dt>Display scale</dt><dd>{scale.toFixed(2)} angstrom (visual only)</dd></dl>{selectedAtom&&displacement?<><h3>Selected periodic atom</h3><p data-testid="phonon-selected-atom">site {selectedAtom.siteIndex} @ [{selectedAtom.ref.imageOffset.join(", ")}] {selectedAtom.species}</p><p data-testid="phonon-selected-displacement">reference [{selectedAtom.canonicalPosition.map(fmt).join(", ")}] | current [{selectedAtom.position.map(fmt).join(", ")}] | displacement [{displacement.map(fmt).join(", ")}] angstrom</p></>:<p>No atom selected.</p>}</div>
    <pre hidden data-testid="phonon-animation-metrics">{JSON.stringify({modeId:mode.mode_id,phase,scale,playing,reducedMotion,supercell:animation.supercell.repeat,atomCount:mapped.scene.atoms.length,vectorCount:showVectors?mapped.vectors.length:0,trailPaths:showTrails?trailsRef.current.size:0,canvasCount:snapshot?.canvasCount??0,contextCount:snapshot?1:0,activeLoops:frameRef.current===null?0:1,drawCalls:snapshot?.metrics.drawCalls??0,mapMs:mapped.mapMs})}</pre><p className="sr-only" aria-live="polite" data-testid="phonon-animation-live-region">{announcement}</p>
  </section>;
}
function Fallback({code,payload,retry}:{code:string;payload:unknown;retry?:()=>void}){return <section className="viewer-renderer-fallback" data-testid="phonon-animation-fallback" role="status"><h3>Phonon animation unavailable</h3><code>{code}</code><p>No renderer or animation loop is active. The inert JSON artifact remains available.</p>{retry?<button type="button" onClick={retry}>Retry renderer</button>:null}<details><summary>Animation JSON summary</summary><pre>{JSON.stringify(summary(payload),null,2)}</pre></details></section>;}
function summary(payload:unknown){if(!payload||typeof payload!=="object"||Array.isArray(payload))return{schema_version:null};const value=payload as Record<string,any>;return{schema_version:value.schema_version??null,mode_id:value.mode?.mode?.mode_id??null,full_json_available_in_preview:true};}
function supportsWebGL(){try{if(typeof navigator!=="undefined"&&/jsdom/i.test(navigator.userAgent))return false;const canvas=document.createElement("canvas");return Boolean(canvas.getContext("webgl2")||canvas.getContext("webgl"));}catch{return false;}}
function fmt(value:number){return Math.abs(value)<.0001&&value!==0?value.toExponential(3):value.toFixed(4);}
