"""Tool adapters for controlled pymatviz and MatterViz execution."""

from .base import BaseToolAdapter
from .context import ToolExecutionContext
from .errors import ToolExecutionError
from .executor import ToolExecutionResult, execute_tool_request
from .platform_builtin import (
    BasicMetricsAdapter,
    BrillouinZoneAdapter,
    ClassificationEvaluationAdapter,
    CompositionSpaceAdapter,
    CompositionSummaryAdapter,
    CorrelationAdapter,
    DistributionSummaryAdapter,
    ErrorDistributionAdapter,
    HistogramAdapter,
    LatticeSummaryAdapter,
    NumericSummaryAdapter,
    OutlierTableAdapter,
    RegressionEvaluationAdapter,
    ScatterAdapter,
    SpacegroupSummaryAdapter,
    StructureCompositionAdapter,
    StructurePreviewMetadataAdapter,
    StructureSummaryAdapter,
    StructureViewerSceneAdapter,
    StructureViewer3DAdapter,
    StructureViewerExportPackageAdapter,
    StructureViewerSceneMetadataAdapter,
    UncertaintyEvaluationAdapter,
    VolumetricDataAdapter,
)
from .pymatviz import (
    ChemSysSunburstAdapter,
    ChemSysTreemapAdapter,
    CoordinationHistAdapter,
    DensityScatterAdapter,
    ElementsHistAdapter,
    FormulaStatisticsAdapter,
    PhononBandAdapter,
    PhononBandDosAdapter,
    PhononAnimationAdapter,
    PhononDosAdapter,
    RdfAdapter,
    XrdPatternAdapter,
)
from .pymatviz.ptable_heatmap import PTableHeatmapAdapter
from .pymatviz.structure_3d import Structure3DAdapter
from .registry import ADAPTER_CLASSES, create_adapter, get_adapter_class

__all__ = [
    "ADAPTER_CLASSES",
    "BaseToolAdapter",
    "BasicMetricsAdapter",
    "BrillouinZoneAdapter",
    "ClassificationEvaluationAdapter",
    "CompositionSpaceAdapter",
    "ChemSysSunburstAdapter",
    "ChemSysTreemapAdapter",
    "CompositionSummaryAdapter",
    "CorrelationAdapter",
    "CoordinationHistAdapter",
    "DensityScatterAdapter",
    "ElementsHistAdapter",
    "ErrorDistributionAdapter",
    "FormulaStatisticsAdapter",
    "PhononBandAdapter",
    "PhononBandDosAdapter",
    "PhononAnimationAdapter",
    "PhononDosAdapter",
    "XrdPatternAdapter",
    "DistributionSummaryAdapter",
    "HistogramAdapter",
    "LatticeSummaryAdapter",
    "NumericSummaryAdapter",
    "OutlierTableAdapter",
    "RegressionEvaluationAdapter",
    "PTableHeatmapAdapter",
    "RdfAdapter",
    "Structure3DAdapter",
    "SpacegroupSummaryAdapter",
    "StructureCompositionAdapter",
    "StructurePreviewMetadataAdapter",
    "StructureSummaryAdapter",
    "StructureViewerSceneAdapter",
    "StructureViewerExportPackageAdapter",
    "StructureViewerSceneMetadataAdapter",
    "StructureViewer3DAdapter",
    "ScatterAdapter",
    "ToolExecutionContext",
    "ToolExecutionError",
    "ToolExecutionResult",
    "UncertaintyEvaluationAdapter",
    "VolumetricDataAdapter",
    "create_adapter",
    "execute_tool_request",
    "get_adapter_class",
]
