from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from pymatgen.core import Lattice, Structure

from mdi_adapters import StructureViewerSceneAdapter
from mdi_adapters.context import ToolExecutionContext
from mdi_artifact_core import validate_viewer_scene, validate_viewer_scene_manifest
from mdi_schemas import ArtifactType
from mdi_tool_registry import load_manifests


ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = ROOT / "docs/phase10f/evidence/phase10f19_periodic_scene_integration"


def main() -> None:
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    shutil.rmtree(output, ignore_errors=True)
    output.mkdir(parents=True)
    runtime = output / "runtime"
    cases = {
        "orthogonal": (Structure(Lattice.cubic(10), ["H", "H"], [[0.98, 0, 0], [0.02, 0, 0]]), 1.0),
        "triclinic": (Structure(Lattice([[4, 0, 0], [1.2, 3.1, 0], [0.7, 0.4, 2.6]]), ["H", "H"], [[0.91, 0.13, 0.77], [0.08, 0.89, 0.12]]), 1.3),
        "self_periodic": (Structure(Lattice.cubic(1), ["H"], [[0, 0, 0]]), 1.01),
    }
    captures: dict[str, object] = {}
    primary: dict[str, object] | None = None
    for case_id, (structure, cutoff) in cases.items():
        artifacts = execute(runtime / case_id, structure, cutoff=cutoff)
        scene = artifacts["viewer_scene.json"]
        manifest = artifacts["viewer_scene_manifest.json"]
        captures[case_id] = {
            "scene_valid": validate_viewer_scene(scene).valid,
            "manifest_valid": validate_viewer_scene_manifest(manifest).valid,
            "bond_count": len(scene["scene"]["bonds"]),
            "bond_ids": [item["id"] for item in scene["scene"]["bonds"]],
            "target_offsets": [item["to"]["image_offset"] for item in scene["scene"]["bonds"]],
            "capabilities": scene["capabilities"],
        }
        if case_id == "orthogonal":
            primary = artifacts
    assert primary is not None
    write_json(output / "viewer_scene.json", primary["viewer_scene.json"])
    write_json(output / "viewer_assets_manifest.json", primary["viewer_scene_manifest.json"])
    (output / "summary.md").write_text(str(primary["summary.md"]), encoding="utf-8")
    write_json(output / "recipe.json", primary["recipe.json"])
    write_json(output / "validation_output.json", {
        "scene": validate_viewer_scene(primary["viewer_scene.json"]).as_dict(),
        "manifest": validate_viewer_scene_manifest(primary["viewer_scene_manifest.json"]).as_dict(),
    })
    write_json(output / "test_captures.json", captures)
    write_json(output / "security_audit.json", {
        "artifact_javascript": False,
        "external_urls": [],
        "external_network_requests": 0,
        "result": "NO_EXTERNAL_NETWORK_REQUESTS",
        "secret_scan": "NO_SECRET_PATTERN_HITS",
    })
    (output / "README.md").write_text(
        "# Phase 10F-19 Periodic Scene Integration Evidence\n\n"
        "Generated by `uv run python apps/web/test/generate-viewer-scene-phase10f19-evidence.py`.\n"
        "The captures use the real adapter and canonical validators. No renderer, external network, or artifact JavaScript is involved.\n",
        encoding="utf-8",
    )
    shutil.rmtree(runtime)
    print("VIEWER_SCENE_PERIODIC_INTEGRATION_EVIDENCE_PASS")
    print("NO_EXTERNAL_NETWORK_REQUESTS")
    print("NO_SECRET_PATTERN_HITS")


def execute(root: Path, structure: Structure, *, cutoff: float) -> dict[str, object]:
    root.mkdir(parents=True)
    context = ToolExecutionContext(
        job_id="job_10f19", project_id="project_10f19", dataset_id="dataset_structure",
        tool_id="structure.viewer_scene", tool_version="1.0.0", adapter_version="1.0.0",
        registry_version=load_manifests().version, artifact_root=root,
        object_store={"structures": [structure]}, resource_limits={"maxStructures": 1, "maxSites": 256, "maxBonds": 2048},
    )
    outputs = StructureViewerSceneAdapter().execute(context, {
        "jobId":"job_10f19", "stepId":"step_001", "toolId":"structure.viewer_scene",
        "inputRefs":[{"refType":"normalized_object","ref":"structures","objectType":"Structure"}],
        "params":{"include_bonds":True,"bond_cutoff_angstrom":cutoff},
        "artifactTypes":[ArtifactType.structure_json.value,ArtifactType.table_json.value,ArtifactType.summary_md.value,ArtifactType.recipe_json.value],
    })
    result: dict[str, object] = {}
    for artifact in outputs:
        raw = (root / artifact.storageKey).read_text(encoding="utf-8")
        result[artifact.name] = json.loads(raw) if artifact.name.endswith(".json") else raw
    return result


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
