"""Phase 7 LLM JSON Planner — public exports."""

from __future__ import annotations

from .planner_prompt import build_planner_prompt
from .analysis_intent import (
    AnalysisIntentError,
    AnalysisIntentRequest,
    AnalysisIntentValidator,
    ClarificationSubmission,
    DeterministicAnalysisIntentBuilder,
    OpenAICompatibleAnalysisIntentBuilder,
    build_analysis_intent_messages,
    detect_goal_language,
    normalize_analysis_goal,
)
from .providers import (
    LLMProviderError,
    LLMPlannerProvider,
    MockLLMProvider,
    OpenAICompatibleProvider,
    PlannerRawResponse,
    PlannerRequest,
    PlannerUserConfig,
)
from .capability_planner import (
    CAPABILITY_PLANNER_VERSION,
    CapabilityContextValidator,
    CapabilityPlanningError,
    CapabilityPlanningResult,
    plan_capabilities,
    project_eligible_candidates,
    resolve_eligibility,
)
from .redaction import is_credential_key, redact_credential_values, redact_params_for_log
from .grounded_interpretation import (
    ArtifactProjectionInput,
    InterpretationError,
    InterpretationResult,
    InterpretationSource,
    ProviderInterpretationProposal,
    build_scientific_evidence_bundle,
    deterministic_interpret,
    no_supported_evidence_result,
    project_artifact,
    provider_safe_projection,
    strict_provider_interpret,
    validate_grounded_interpretation,
)

__all__ = [
    "ArtifactProjectionInput",
    "AnalysisIntentError",
    "AnalysisIntentRequest",
    "AnalysisIntentValidator",
    "InterpretationError",
    "InterpretationResult",
    "InterpretationSource",
    "CAPABILITY_PLANNER_VERSION",
    "CapabilityContextValidator",
    "CapabilityPlanningError",
    "CapabilityPlanningResult",
    "ClarificationSubmission",
    "DeterministicAnalysisIntentBuilder",
    "OpenAICompatibleAnalysisIntentBuilder",
    "build_analysis_intent_messages",
    "build_planner_prompt",
    "detect_goal_language",
    "is_credential_key",
    "LLMProviderError",
    "LLMPlannerProvider",
    "MockLLMProvider",
    "OpenAICompatibleProvider",
    "PlannerRawResponse",
    "PlannerRequest",
    "PlannerUserConfig",
    "ProviderInterpretationProposal",
    "build_scientific_evidence_bundle",
    "deterministic_interpret",
    "no_supported_evidence_result",
    "plan_capabilities",
    "project_eligible_candidates",
    "project_artifact",
    "provider_safe_projection",
    "redact_credential_values",
    "redact_params_for_log",
    "resolve_eligibility",
    "strict_provider_interpret",
    "validate_grounded_interpretation",
    "normalize_analysis_goal",
]
